---
# file: yavdr07-headless.yml
# this playbook set up a headless yaVDR 0.7 installation

- name: set up a headless yaVDR server
  hosts: all
  become: true
  roles:
    - yavdr-common
    - collect-facts              # query system facts
    - vdr
    - lifeguardng                # install and configure vdr-addon-lifeguard-ng
    - yavdr-network
    - samba-install
    - samba-config
    - nfs-server
    - grub-config
    - autoinstall-satip          # install vdr-plugin-satip if a Sat>IP server has been found
    - autoinstall-pvr350         # install vdr-plugin-pvr350 if a matching card is detected
    - autoinstall-hauppauge-pvr  # install vdr-plugin-pvrinput if a matching card is found
    - autoinstall-dvbsddevice    # install vdr-plugin-dvbsddevice if a matching card is detected
    - autoinstall-dvbsky-firmware # download and install required firmware files for dvbsky cards
    - autoinstall-firmware       # download and install firmware files for dvb devices
    #- epgd                      # install vdr-epg-daemon
    #- channelpedia               # upload channels.conf to channelpedia (see role description in Manual)
    - wakeup
  tags:
    - always
  handlers:
    - import_tasks: handlers/main.yml
