---
# file: yavdr07-headless.yml
# this playbook set up a headless yaVDR 0.7 installation

- name: set up a headless yaVDR server
  hosts: all
  become: true
  roles:
    - yavdr-common
    - collect-facts              # query system facts
    - vdr
    - yavdr-network
    - samba-install
    - samba-config
    - nfs-server
    - grub-config
    - autoinstall-satip
    - wakeup
  tags:
    - always
  handlers:
    - import_tasks: handlers/main.yml
